#!/usr/bin/env python3
"""V10 runner — full SMC framework engine.

Separate Render service from V9. DRY_RUN. Reads same wallet for sizing math.
Polls production /orderbook/<coin> for wall confluence (Stage 5).
Polls HL public API for 4H, 1H, 5m candles.

Flow per coin per tick (subject to tier cadence):
  1. Fetch 4H bars → detect unmitigated OBs (Stage 1)
  2. Check if current price near unmitigated OB (Stage 2)
  3. Fetch 1H bars → MTF structure check (Stage 3)
  4. Fetch 5m bars → sweep + MSS + LTF OB (Stage 4)
  5. Fetch /orderbook/<coin> → verify wall at LTF OB body (Stage 5)
  6. Build setup with limit at OB body, SL past OB wick + 1 tick (Stage 6)
  7. Place orders (DRY) or log only

State at /var/data/pole_state_v10.json. Production untouched.
"""
import json, os, sys, time, traceback, urllib.request
from datetime import datetime, timezone
from typing import Optional
from concurrent.futures import ThreadPoolExecutor

# PM Phase 2 client. No-op unless PM_CHECK_ENABLED=1. Fail-closed on PM down.
try:
    import pm_client
except ImportError:
    pm_client = None

import v10_blacklist  # 5-consec-loss runtime blacklist
from coin_tiers import (DepthBaseline, get_tier, coins_for_tick, ALL_COINS, get_tier_number,
                          refresh_hl_volumes, get_volume_threshold, get_volume)
from regime_gate import classify_regime, is_v10_allowed
from pole_engine_v10 import (
    detect_consolidation_obs, get_unmitigated_zone_at, mtf_structure_intact,
    detect_ltf_setup, build_setup, OBZone, Setup, atr,
)
# V9 wall logic for Stage 5 confluence
from pole_engine_v9 import cluster_walls, WallTracker

PRECOG_URL       = os.environ.get('PRECOG_URL', 'https://precog-i8c3.onrender.com')
HL_API           = 'https://api.hyperliquid.xyz/info'
DRY_RUN          = os.environ.get('DRY_RUN', '1') == '1'
LIVE             = os.environ.get('LIVE_TRADING', '0') == '1' and not DRY_RUN
PRIVATE_KEY      = os.environ.get('HL_PRIVATE_KEY', '')
WALLET           = os.environ.get('HL_ADDRESS') or os.environ.get('HYPERLIQUID_ACCOUNT', '')
RISK_PCT         = float(os.environ.get('RISK_PCT', '0.0025'))
LEVERAGE         = int(os.environ.get('LEVERAGE', '5'))
MAX_POSITIONS    = int(os.environ.get('MAX_POSITIONS', '6'))
MAX_PENDING      = int(os.environ.get('MAX_PENDING_LIMITS', '12'))
MAX_NOTIONAL_PCT = float(os.environ.get('MAX_NOTIONAL_PCT', '0.20'))
# Fixed-notional override. When > 0, calc_size() returns exactly this dollar
# notional per trade, bypassing risk-based sizing. Capped by leverage only.
FIXED_NOTIONAL_USD = float(os.environ.get('FIXED_NOTIONAL_USD', '0'))
POLL_INTERVAL_S  = int(os.environ.get('POLL_INTERVAL_S', '60'))  # slower than V9, framework needs less frequency
SCAN_WORKERS     = int(os.environ.get('SCAN_WORKERS', '6'))
CANDLE_CACHE_S   = int(os.environ.get('CANDLE_CACHE_S', '300'))  # 5min cache for 4h/1h candles
SETUP_EXPIRE_S   = int(os.environ.get('SETUP_EXPIRE_S', '14400'))  # 4h to fill limit
WALL_CONFLUENCE  = os.environ.get('WALL_CONFLUENCE', '1') == '1'
# Council #3 diagnostic: off by default. Set DIAGNOSTIC_DIR_FILTER=1 to reject SELL setups
# when 1H EMA20 > EMA50 (bullish regime), and reject BUY setups when 1H EMA20 < EMA50 (bearish).
# Off until n>=30 confirms a real directional bias requires defending.
DIAGNOSTIC_DIR_FILTER = os.environ.get('DIAGNOSTIC_DIR_FILTER', '0') == '1'
MIN_WALL_USD     = float(os.environ.get('MIN_WALL_USD', '100000'))  # min wall at LTF OB

# ============================================================================
# Council Fixes 1-4 (validated 180d backtest: WR 24.9% → 34.1%, PF 0.6 → 1.72)
# ============================================================================
WALL_REQUIRED      = os.environ.get('WALL_REQUIRED', '1') == '1'        # Fix 1
SINGLE_TP_R        = float(os.environ.get('SINGLE_TP_R', '3.5'))        # Fix 2: 0=disabled, >0=single target at this R
REGIME_GATE        = os.environ.get('REGIME_GATE', '1') == '1'           # Fix 3
SL_ATR_MULT        = float(os.environ.get('SL_ATR_MULT', '0.5'))        # Fix 4: SL buffer = max(ticks, this × ATR_5m)
COINS_OVERRIDE   = os.environ.get('COINS', '').strip()
COINS            = ([c.strip().upper() for c in COINS_OVERRIDE.split(',') if c.strip()]
                    if COINS_OVERRIDE else list(ALL_COINS))
STATE_FILE       = os.environ.get('STATE_FILE', '/var/data/pole_state_v10.json')

state = {
    'balance': 0.0, 'positions': {}, 'pending': {},
    'tick_count': 0, 'last_tick_t': 0,
    'fires_total': 0,
    'qualified_setups': 0, 'wall_confluence_blocked': 0,
    'wall_present': 0,           # framework setup also had a confirmed wall (additive confluence)
    'wall_absent': 0,            # framework setup fired without wall confluence (still a valid trade)
    'fires_path_4h': 0,          # setups generated by Path A (4H/1H/5m)
    'fires_path_1h': 0,          # setups generated by Path B (1H/15m/5m)
    'stage_drops': {'no_4h_data':0,'no_zones':0,'no_5m_recent':0,'not_at_zone':0,
                    'no_1h_data':0,'mtf_block':0,'no_5m_data':0,'no_ltf':0,
                    'already_fired':0,'build_setup_fail':0},
    # Stage 4 (LTF) sub-drop instrumentation
    'ltf_drops': {'no_pivots':0,'no_atr':0,'no_sweep':0,'no_local_window':0,
                   'no_mss':0,'no_ob_window':0},
    'build_fail_drops': {'no_tp_at_all':0,'wrong_side_tp':0,'zero_risk':0,
                          'risk_over_10pct':0,'rr_too_low':0},
    # Diagnostic counters (Council #3)
    'micro_samples': 0,           # count of MICRO log lines emitted
    'build_fail_history': [],     # last 50 BUILD-FAIL records with full pricing data
    # Outcome tracker (paper P&L)
    'wins_tp1_tp2': 0,        # both TPs hit
    'wins_tp1_be': 0,         # TP1 hit, runner stopped at breakeven (still net +)
    'wins_tp1_betimeout': 0,  # TP1 hit, runner force-closed at BE after RUNNER_BE_TIMEOUT_S
    'losses_sl': 0,           # full loss before TP1
    'expired_unfilled': 0,    # entry never filled within SETUP_EXPIRE_S
    'closed_open_eow': 0,     # filled but neither SL nor TP1 hit before tracker timeout
    'pnl_pct_total': 0.0,     # cumulative paper PnL %, fee-adjusted
    'recent_trades': [],      # last 20 closed trades for inspection
    # Persistent OB-fired dedup (replaces in-memory COIN_FIRED_OBS)
    'fired_obs': {},          # coin -> list of [body_top, body_bottom]
    'log': [],
}

def log(msg):
    line = f"[{datetime.now(timezone.utc).strftime('%H:%M:%SZ')}] {msg}"
    print(line, flush=True)
    state['log'].append(line)
    if len(state['log']) > 500: state['log'] = state['log'][-500:]

def http_get(url, timeout=10):
    try: return json.loads(urllib.request.urlopen(url, timeout=timeout).read())
    except: return None

def http_post(url, body, timeout=10):
    try:
        req = urllib.request.Request(url, data=json.dumps(body).encode(),
                                       headers={'Content-Type':'application/json'})
        return json.loads(urllib.request.urlopen(req, timeout=timeout).read())
    except: return None

def fetch_orderbook(coin): return http_get(f"{PRECOG_URL}/orderbook/{coin}")
def fetch_account(): return http_post(HL_API, {'type':'clearinghouseState','user':WALLET}) if WALLET else None

def fetch_candles(coin, interval, days):
    end = int(time.time()*1000); start = end - days*86400000
    raw = http_post(HL_API, {'type':'candleSnapshot','req':{'coin':coin,'interval':interval,'startTime':start,'endTime':end}})
    if not raw: return []
    bars = [{'t':b['t'],'o':float(b['o']),'h':float(b['h']),'l':float(b['l']),'c':float(b['c']),'v':float(b['v'])} for b in raw]
    bars.sort(key=lambda x: x['t'])
    return bars

# Cache: (coin, interval) → (timestamp, bars)
CANDLE_CACHE = {}
# HL coin tick sizes (absolute price increment per coin)
COIN_TICKS = {}

def fetch_tick_sizes():
    """Pull HL meta + asset contexts. Derive tick_size from markPx decimal precision."""
    raw = http_post(HL_API, {'type':'metaAndAssetCtxs'})
    if not raw or len(raw) < 2: return
    universe, ctxs = raw[0]['universe'], raw[1]
    for u, c in zip(universe, ctxs):
        name = u['name']
        mark = c.get('markPx', '')
        if not mark: continue
        if '.' in mark:
            px_decimals = len(mark.split('.')[1])
        else:
            px_decimals = 0
        COIN_TICKS[name] = 10 ** -px_decimals
    log(f"Loaded tick sizes for {len(COIN_TICKS)} coins")

def get_candles_cached(coin, interval, days):
    key = (coin, interval)
    cached = CANDLE_CACHE.get(key)
    if cached and time.time() - cached[0] < CANDLE_CACHE_S:
        return cached[1]
    bars = fetch_candles(coin, interval, days)
    CANDLE_CACHE[key] = (time.time(), bars)
    return bars

# Per-coin setup deduplication: don't re-fire same OB
def already_fired(coin, ob_body_top, ob_body_bottom, tolerance=0.001):
    fired = state['fired_obs'].get(coin, [])
    for entry in fired:
        t, b = entry[0], entry[1]
        if abs(t - ob_body_top) / ob_body_top < tolerance and abs(b - ob_body_bottom) / ob_body_bottom < tolerance:
            return True
    return False

def mark_fired(coin, ob_body_top, ob_body_bottom):
    lst = state['fired_obs'].setdefault(coin, [])
    lst.append([ob_body_top, ob_body_bottom])
    if len(lst) > 50:
        # Trim oldest, keep last 50
        state['fired_obs'][coin] = lst[-50:]

def calc_size(balance, entry, sl):
    if balance <= 0 or entry <= 0: return 0, 0
    # FIXED_NOTIONAL_USD override: every trade is exactly this dollar notional,
    # capped only by available leverage. Skips RISK_PCT / sl_dist computation.
    if FIXED_NOTIONAL_USD > 0:
        notional_cap_lev = balance * LEVERAGE
        notional = min(FIXED_NOTIONAL_USD, notional_cap_lev)
        return notional / entry, notional
    risk_amt = balance * RISK_PCT
    sl_dist = abs(entry - sl) / entry
    if sl_dist <= 0: return 0, 0
    notional = min(risk_amt / sl_dist, balance * LEVERAGE, balance * MAX_NOTIONAL_PCT * LEVERAGE)
    return notional / entry, notional

def load_state():
    try:
        if os.path.exists(STATE_FILE):
            with open(STATE_FILE) as f:
                loaded = json.load(f)
                state.update({k: v for k, v in loaded.items() if k in state})
                log(f"Loaded state: pos={len(state['positions'])} pend={len(state['pending'])}")
    except Exception as e: log(f"load_state err: {e}")

def save_state():
    try:
        os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
        with open(STATE_FILE, 'w') as f: json.dump(state, f, default=str)
    except Exception as e: log(f"save_state err: {e}")

EXCHANGE = None
WALL_TRACKER = WallTracker(max_history=30)
DEPTH_BASE = DepthBaseline(window=20, multiplier=8.0)


# ───────── PUSH STATE TO PRECOG (visibility for landing page) ─────────
# V10 is a background_worker — no public HTTP. Instead, push a state
# snapshot to precog every tick. precog stores the latest push and
# serves it via /api/v10_state. The landing page reads that endpoint
# alongside the other paper engines.
#
# Push is fire-and-forget in a daemon thread. Network failures swallowed.
import threading as _bg

DASH_URL = os.environ.get('DASH_URL', '').rstrip('/')
DASH_PUSH_SECRET = os.environ.get('DASH_PUSH_SECRET', '')


def _build_v10_state_payload():
    """Convert V10's internal `state` dict into the same /state shape that
    the vol engines expose, so the landing's PAPER_ENGINES fetcher can
    consume it without special-casing."""
    open_trades = []
    for coin, p in state.get('positions', {}).items():
        try:
            open_trades.append({
                'cloid': p.get('cloid', f"v10sw_{coin}_{p.get('fill_t','?')}"),
                'coin': coin,
                'side': 'B' if p.get('side') in ('long', 'B', 'L') else 'A',
                'size': float(p.get('size_coin') or p.get('size') or 0),
                'entry_px': float(p.get('fill_price') or 0),
                'sl_px': float(p.get('sl') or 0),
                'tp_px': float(p.get('tp1') or p.get('tp2') or 0),
                'notional': float(p.get('notional_usd') or 0),
                'leverage': p.get('leverage') or LEVERAGE,
                'ts_open': int(p.get('fill_t') or 0),
            })
        except Exception:
            continue
    try:
        bl_state = v10_blacklist.get_state_snapshot()
    except Exception:
        bl_state = {}
    return {
        'service': 'V10',
        'ts': int(time.time() * 1000),
        'mode_effective': 'paper' if not LIVE else 'live',
        'open_trades': open_trades,
        'pending_count': len(state.get('pending', {})),
        'tick_count': state.get('tick_count', 0),
        'fires_total': state.get('fires_total', 0),
        'blacklist': bl_state,
        'universe_size': len(COINS),
    }


def _push_state_to_precog():
    if not DASH_URL or not DASH_PUSH_SECRET:
        return
    try:
        payload = _build_v10_state_payload()
        body = json.dumps(payload).encode()
        req = urllib.request.Request(
            f"{DASH_URL}/api/v10_state",
            data=body,
            headers={
                'Content-Type': 'application/json',
                'X-Dash-Secret': DASH_PUSH_SECRET,
            },
            method='POST',
        )
        urllib.request.urlopen(req, timeout=4).read()
    except Exception:
        pass  # swallow — never block scan loop on visibility push


def _push_state_async():
    _bg.Thread(target=_push_state_to_precog, daemon=True).start()

def init_sdk():
    if DRY_RUN:
        log("SDK skipped (DRY_RUN)"); return None
    try:
        from hyperliquid.exchange import Exchange
        from hyperliquid.utils import constants
        from eth_account import Account
        wallet = Account.from_key(PRIVATE_KEY)
        ex = Exchange(wallet, constants.MAINNET_API_URL, account_address=WALLET)
        log(f"SDK initialized (LIVE)")
        return ex
    except Exception as e:
        log(f"SDK init failed: {e}"); return None

def place_limit(coin, is_buy, size, price, reduce_only=False, label=''):
    if DRY_RUN or not LIVE or EXCHANGE is None:
        log(f"  [DRY] LIMIT {coin} {'BUY' if is_buy else 'SELL'} sz={size:.6f} px={price:.6f} {label}")
        return {'status':'ok','response':{'data':{'statuses':[{'resting':{'oid':int(time.time()*1000000)}}]}}}
    try:
        return EXCHANGE.order(coin, is_buy, size, price, {'limit':{'tif':'Gtc'}}, reduce_only=reduce_only)
    except Exception as e:
        log(f"  limit err {coin}: {e}"); return None

def fetch_hl_l2(coin):
    """Direct HL L2Book fetch for HL-native tokens not on multi-venue feed."""
    raw = http_post(HL_API, {'type': 'l2Book', 'coin': coin})
    if not raw or 'levels' not in raw: return None
    levels = raw['levels']
    if len(levels) < 2: return None
    bids_raw, asks_raw = levels[0], levels[1]
    # HL format: each level = {'px': '...', 'sz': '...', 'n': N}
    bids = [{'price': float(l['px']), 'size': float(l['sz']),
             'usd': float(l['px'])*float(l['sz'])} for l in bids_raw]
    asks = [{'price': float(l['px']), 'size': float(l['sz']),
             'usd': float(l['px'])*float(l['sz'])} for l in asks_raw]
    mid = (bids[0]['price'] + asks[0]['price']) / 2 if bids and asks else 0
    return {'mid': mid, 'bids': bids, 'asks': asks}


def microstructure_metrics(ob: dict) -> dict:
    """Compute spread_bps + top-of-book depth for noise-floor study (Step 3, logged not used).

    Returns: {spread_bps, top_bid_usd, top_ask_usd, depth_10bp_usd}
    depth_10bp_usd = sum of bid+ask USD within 10bp of mid (proxy for thin/thick books).
    """
    if not ob or not ob.get('bids') or not ob.get('asks'): return {}
    top_bid = ob['bids'][0]['price']
    top_ask = ob['asks'][0]['price']
    mid = (top_bid + top_ask) / 2
    if mid <= 0: return {}
    spread_bps = ((top_ask - top_bid) / mid) * 10000
    band = mid * 0.001  # 10 bps either side
    depth_10bp = (sum(b['usd'] for b in ob['bids'] if b['price'] >= mid - band) +
                   sum(a['usd'] for a in ob['asks'] if a['price'] <= mid + band))
    return {
        'spread_bps': round(spread_bps, 2),
        'top_bid_usd': round(ob['bids'][0]['usd'], 0),
        'top_ask_usd': round(ob['asks'][0]['usd'], 0),
        'depth_10bp_usd': round(depth_10bp, 0),
    }


def wall_confluence_check(coin: str, ob_body_top: float, ob_body_bottom: float, side: str) -> tuple:
    """Stage 5: verify there's a wall at the LTF OB (production aggregator OR HL L2 fallback).

    Threshold is volume-driven per coin: K × sqrt(24h_notional_volume).
    Falls back to MIN_WALL_USD env var if volume cache is empty.
    HL-L2 fallback uses 40% of computed threshold (single-venue depth).
    """
    if not WALL_CONFLUENCE:
        return True, 0, 'wall confluence disabled'
    ob = fetch_orderbook(coin)
    used_hl_fallback = False
    if not ob or not ob.get('mid'):
        ob = fetch_hl_l2(coin)
        used_hl_fallback = True
        if not ob or not ob.get('mid'):
            return False, 0, 'no orderbook data (prod + HL both empty)'
    bids = ob.get('bids', [])
    asks = ob.get('asks', [])
    target_price = ob_body_bottom if side == 'BUY' else ob_body_top
    relevant_orders = bids if side == 'BUY' else asks
    cluster_usd = sum(o['usd'] for o in relevant_orders
                       if abs(o['price'] - target_price) / target_price < 0.003)
    # Volume-driven base threshold; fall back to env-var if no volume cached
    base_thr = get_volume_threshold(coin)
    if base_thr <= 5000.0:  # floor returned — volume not yet loaded
        base_thr = MIN_WALL_USD
    # HL single-venue gets 40% of the multi-venue threshold
    threshold = base_thr * 0.4 if used_hl_fallback else base_thr
    passed = cluster_usd >= threshold
    src = 'HL-L2' if used_hl_fallback else 'multi-venue'
    vol = get_volume(coin)
    vol_str = f"vol=${(vol or 0)/1e6:.1f}M" if vol else "vol=?"

    # Step 3 (council): noise-floor instrumentation. Logged but NOT acted upon.
    # Goal: 7-day data set of (coin, tier, spread_bps, depth_10bp_usd) per qualified setup
    # so we can later validate whether tier/cap actually predicts noise floor or whether
    # spread+depth is the better proxy.
    micro = microstructure_metrics(ob)
    if micro:
        state['micro_samples'] = state.get('micro_samples', 0) + 1
        log(f"  MICRO {coin} tier={get_tier(coin) or '?'} spread={micro['spread_bps']}bp "
            f"top_bid=${micro['top_bid_usd']:.0f} top_ask=${micro['top_ask_usd']:.0f} "
            f"depth_10bp=${micro['depth_10bp_usd']:.0f}")

    return passed, cluster_usd, f"{src} {vol_str} target={target_price:.6f} cluster=${cluster_usd/1000:.0f}k thr=${threshold/1000:.0f}k"

def _evaluate_path(coin: str, htf_label: str, htf_days: int,
                    mtf_label: str, mtf_days: int) -> Optional[Setup]:
    """Run the framework pipeline for one TF triplet. HTF zone -> MTF structure -> 5m LTF.

    htf_label/mtf_label: HL candle interval ('4h', '1h', '15m', '5m').
    Returns Setup with path_label = htf_label, or None if any stage fails.
    """
    sd = state['stage_drops']

    bars_htf = get_candles_cached(coin, htf_label, htf_days)
    if len(bars_htf) < 30: sd['no_4h_data'] += 1; return None

    zones = detect_consolidation_obs(bars_htf, htf_label, displacement_atr_mult=1.5,
                                       min_consol_bars=2, max_consol_bars=8)
    if not zones: sd['no_zones'] += 1; return None

    bars_5m_recent = get_candles_cached(coin, '5m', 1)
    if len(bars_5m_recent) < 5: sd['no_5m_recent'] += 1; return None
    current_price = bars_5m_recent[-1]['c']
    cur_htf_idx = len(bars_htf) - 1
    zone, bias = get_unmitigated_zone_at(zones, cur_htf_idx, current_price, proximity_pct=0.005)
    if zone is None: sd['not_at_zone'] += 1; return None

    log(f"  STAGE2-PASS [{htf_label}] {coin} {bias} @ {zone.type} zone [{zone.body_bottom:.6f}-{zone.body_top:.6f}]")

    bars_mtf = get_candles_cached(coin, mtf_label, mtf_days)
    if len(bars_mtf) < 30: sd['no_1h_data'] += 1; return None
    if not mtf_structure_intact(bars_mtf, bias): sd['mtf_block'] += 1; return None

    log(f"  STAGE3-PASS [{htf_label}] {coin} MTF intact")

    bars_5m = get_candles_cached(coin, '5m', 7)
    if len(bars_5m) < 30: sd['no_5m_data'] += 1; return None
    bars_5m_window = bars_5m[-50:]
    ltf, ltf_drop = detect_ltf_setup(bars_5m_window, bias)
    if ltf is None:
        sd['no_ltf'] += 1
        if ltf_drop:
            state['ltf_drops'][ltf_drop] = state['ltf_drops'].get(ltf_drop, 0) + 1
        return None

    log(f"  STAGE4-PASS [{htf_label}] {coin} {ltf['side']} ob_body=[{ltf['ob_body_bottom']:.6f}-{ltf['ob_body_top']:.6f}]")

    if already_fired(coin, ltf['ob_body_top'], ltf['ob_body_bottom']):
        sd['already_fired'] += 1; return None

    # Council #3 diagnostic: 1H trend filter (off by default). Reject side-against-regime.
    if DIAGNOSTIC_DIR_FILTER:
        try:
            from pole_engine_v10 import atr  # cheap, already imported elsewhere
        except Exception: pass
        bars_1h_filt = get_candles_cached(coin, '1h', 7)
        if len(bars_1h_filt) >= 50:
            closes = [b['c'] for b in bars_1h_filt]
            ema20 = sum(closes[-20:]) / 20
            ema50 = sum(closes[-50:]) / 50
            regime_bull = ema20 > ema50
            if (ltf['side'] == 'SELL' and regime_bull) or (ltf['side'] == 'BUY' and not regime_bull):
                state.setdefault('dir_filter_blocked', 0)
                state['dir_filter_blocked'] = state.get('dir_filter_blocked', 0) + 1
                log(f"  DIR-FILTER-BLOCK [{htf_label}] {coin} {ltf['side']} (regime={'bull' if regime_bull else 'bear'})")
                return None

    # Stage 5: wall confluence (council Fix 1: REQUIRED when WALL_REQUIRED=1)
    state['qualified_setups'] += 1
    side_for_wall = ltf['side']
    wall_passed, wall_usd, wall_notes = wall_confluence_check(
        coin, ltf['ob_body_top'], ltf['ob_body_bottom'], side_for_wall
    )
    if wall_passed:
        state['wall_present'] += 1
        log(f"  WALL-PRESENT [{htf_label}] {coin} {side_for_wall} ${wall_usd/1000:.0f}k")
    else:
        state['wall_absent'] += 1
        log(f"  WALL-ABSENT  [{htf_label}] {coin} {side_for_wall} ({wall_notes})")
        if WALL_REQUIRED:
            sd['wall_required_block'] = sd.get('wall_required_block', 0) + 1
            return None

    # Stage 6: build setup. For Path B (1H htf), TP2 comes from 1H zones, not 4H.
    tick = COIN_TICKS.get(coin, 0.0001)
    # 3-tier SL buffer scaling (council-approved). Tighter coins get tighter stops; noisy coins
    # get wider buffers to survive normal wick-hunting on illiquid books.
    coin_tier = get_tier_number(coin)   # default to noisiest tier if unknown
    if coin_tier <= 2:        # BTC, ETH, HYPE, SOL, TON, ZEC
        sl_ticks, sl_min = 2, 0.0005
    elif coin_tier <= 4:      # mid + small cap
        sl_ticks, sl_min = 4, 0.0010
    else:                     # micro / illiquid
        sl_ticks, sl_min = 6, 0.0020
    setup, build_drop = build_setup(coin, ltf, zone, bars_mtf, bars_htf, zones,
                          tick_size=tick, sl_buffer_ticks=sl_ticks, sl_min_buffer_pct=sl_min, min_rr_to_tp1=1.5,
                          sl_atr_mult=SL_ATR_MULT, single_tp_R=SINGLE_TP_R)
    if setup is None:
        sd['build_setup_fail'] += 1
        # Sub-reason aggregation
        bd = state.setdefault('build_fail_drops',
            {'no_tp_at_all':0,'wrong_side_tp':0,'zero_risk':0,'risk_over_10pct':0,'rr_too_low':0})
        if build_drop:
            if build_drop.startswith('rr_too_low'):
                bd['rr_too_low'] += 1
            elif build_drop in bd:
                bd[build_drop] += 1

        # Council #3: full pricing capture for offline analysis. Recompute the same
        # way build_setup did using the inputs we have; no engine signature change.
        try:
            from pole_engine_v10 import find_next_liquidity, htf_target
            side = ltf['side']
            if side == 'BUY':
                entry = ltf['ob_body_top']; wick = ltf['ob_wick_bottom']
                buf = max(sl_ticks * tick, sl_min * wick); sl = wick - buf
            else:
                entry = ltf['ob_body_bottom']; wick = ltf['ob_wick_top']
                buf = max(sl_ticks * tick, sl_min * wick); sl = wick + buf
            tp1 = find_next_liquidity(bars_mtf, side, entry)
            tp2_z = htf_target(zones, side, entry)
            sl_dist_pct = abs(entry - sl) / entry if entry else 0
            tp1_dist_pct = abs(tp1 - entry) / entry if (tp1 and entry) else 0
            rr1 = (tp1_dist_pct / sl_dist_pct) if sl_dist_pct else 0
            rec = {
                'coin': coin, 'side': side, 'path': htf_label, 'tier': get_tier(coin) or '?',
                'reason': build_drop, 'entry': entry, 'sl': sl, 'tp1': tp1, 'tp2': tp2_z,
                'wick': wick, 'buffer': buf,
                'sl_dist_pct': round(sl_dist_pct*100, 3),
                'tp1_dist_pct': round(tp1_dist_pct*100, 3),
                'rr1': round(rr1, 2),
                'sweep_wick': ltf.get('sweep_wick'),
                'mss_break': ltf.get('mss_break'),
                't': int(time.time()*1000),
            }
            hist = state.setdefault('build_fail_history', [])
            hist.append(rec)
            if len(hist) > 50:
                state['build_fail_history'] = hist[-50:]
            log(f"  BUILD-FAIL [{htf_label}] {coin} {side} ({build_drop or 'unknown'}) "
                f"entry={entry:.6f} sl={sl:.6f} tp1={(tp1 or 0):.6f} sl_dist={sl_dist_pct*100:.2f}% tp1_dist={tp1_dist_pct*100:.2f}% rr1={rr1:.2f}")
        except Exception as e:
            log(f"  BUILD-FAIL [{htf_label}] {coin} {ltf['side']} ({build_drop or 'unknown'}) — diag err: {e}")
        return None

    if wall_passed:
        setup.notes += f" | wall ${wall_usd/1000:.0f}k ✓"
    else:
        setup.notes += " | no wall"
    # Stash for persistence on pending/outcome records (split-analysis later)
    setup.wall_present = wall_passed
    setup.wall_usd = wall_usd
    setup.path_label = htf_label

    return setup


def evaluate_coin(coin: str) -> Optional[Setup]:
    """Run BOTH framework paths for a coin. Returns first valid setup (Path A wins ties).

    Path A: 4H zone -> 1H structure -> 5m LTF (slower, cleaner setups)
    Path B: 1H zone -> 15m structure -> 5m LTF (faster cadence, more frequent)
    `already_fired` dedup guards against double-firing on the same LTF OB body.
    """
    setup_a = _evaluate_path(coin, htf_label='4h', htf_days=60, mtf_label='1h', mtf_days=14)
    if setup_a is not None:
        return setup_a
    return _evaluate_path(coin, htf_label='1h', htf_days=30, mtf_label='15m', mtf_days=5)


def place_setup(setup: Setup):
    """Place the bracket: entry limit + SL + TP1 (50%) + TP2 (50%)."""
    coin = setup.coin
    if coin in state['positions']:
        log(f"  skip {coin}: position exists"); return
    if any(p['coin']==coin for p in state['pending'].values()):
        log(f"  skip {coin}: pending exists"); return
    if len(state['pending']) >= MAX_PENDING:
        log(f"  skip {coin}: max pending"); return

    size, notional = calc_size(state['balance'], setup.entry_price, setup.sl_price)
    if size <= 0:
        log(f"  size=0 skip"); return

    # PM Phase 2 pre-trade gate. Fail-closed if PM unreachable when enabled.
    # No-op when pm_client missing or PM_CHECK_ENABLED unset (default).
    if pm_client is not None and pm_client.PM_CHECK_ENABLED:
        is_buy_for_check = (setup.side == 'BUY')
        pm_resp = pm_client.check_pretrade(
            coin=coin,
            side='B' if is_buy_for_check else 'A',
            notional=notional,
            sl_distance_pct=setup.sl_distance_pct,
            is_live=bool(LIVE),
            engine=os.environ.get('ENGINE_NAME', 'V10'),
        )
        if not pm_resp.get('allow'):
            log(f"  PM-DENIED {coin} reason={pm_resp.get('reason')} cap=${pm_resp.get('capital_remaining')}")
            return

    half = size / 2.0
    log(f"PLACE {setup.side} {coin} entry={setup.entry_price:.6f} sl={setup.sl_price:.6f} "
        f"tp1={setup.tp1_price:.6f} tp2={setup.tp2_price:.6f} "
        f"R:R1={setup.rr_to_tp1:.2f} R:R2={setup.rr_to_tp2:.2f} "
        f"sl_dist={setup.sl_distance_pct*100:.2f}% sz={size:.6f} ${notional:.2f}")
    log(f"  {setup.notes}")

    is_buy = (setup.side == 'BUY')
    
    # Register entry cloid with PM (best-effort) so PM can attribute the fill.
    # Done before place_limit. SL/TP cloids would need separate registration if
    # they're tracked individually; for now only the entry side is attributed.
    if pm_client is not None and pm_client.PM_CHECK_ENABLED:
        try:
            entry_cloid = getattr(setup, 'entry_cloid', None) or f"v10sw_{coin}_{int(time.time())}"
            pm_client.register_cloid(cloid=entry_cloid, coin=coin,
                                       engine=os.environ.get('ENGINE_NAME', 'V10'))
        except Exception as e:
            log(f"  pm.register_cloid err (non-fatal): {e}")
    
    or_res = place_limit(coin, is_buy, size, setup.entry_price, reduce_only=False, label='ENTRY')
    if not or_res: return
    entry_oid = or_res.get('response',{}).get('data',{}).get('statuses',[{}])[0].get('resting',{}).get('oid')

    sl_res  = place_limit(coin, not is_buy, size, setup.sl_price,  reduce_only=True, label='SL')
    if SINGLE_TP_R > 0:
        # Council Fix 2: single all-or-nothing target. tp1 == tp2; place ONE order at full size.
        tp1_res = place_limit(coin, not is_buy, size, setup.tp1_price, reduce_only=True, label='TP')
        tp2_res = tp1_res  # alias so existing bracket-failure logic doesn't break
    else:
        tp1_res = place_limit(coin, not is_buy, half, setup.tp1_price, reduce_only=True, label='TP1')
        tp2_res = place_limit(coin, not is_buy, half, setup.tp2_price, reduce_only=True, label='TP2')

    # Atomic bracket guarantee — only meaningful in LIVE mode
    if LIVE and EXCHANGE is not None:
        bracket_failed = (not sl_res) or (not tp1_res) or (not tp2_res)
        if bracket_failed:
            log(f"  BRACKET-FAIL {coin} sl={bool(sl_res)} tp1={bool(tp1_res)} tp2={bool(tp2_res)} — rolling back")
            # 1) Cancel any of the bracket legs that DID land
            for leg_res, leg_name in ((sl_res,'SL'), (tp1_res,'TP1'), (tp2_res,'TP2')):
                if not leg_res: continue
                leg_oid = leg_res.get('response',{}).get('data',{}).get('statuses',[{}])[0].get('resting',{}).get('oid')
                if leg_oid:
                    try: EXCHANGE.cancel(coin, leg_oid)
                    except Exception as e: log(f"    cancel {leg_name} err: {e}")
            # 2) Cancel the entry if still resting
            if entry_oid:
                try: EXCHANGE.cancel(coin, entry_oid)
                except Exception as e: log(f"    cancel ENTRY err: {e}")
            # 3) If entry already filled (race), force a market close to avoid naked exposure
            try:
                acct = fetch_account()
                pos_sz = 0.0
                for ap in (acct or {}).get('assetPositions', []):
                    if ap.get('position', {}).get('coin') == coin:
                        pos_sz = float(ap['position'].get('szi') or 0.0); break
                if abs(pos_sz) > 0:
                    log(f"    entry filled before rollback — emergency market close sz={pos_sz}")
                    EXCHANGE.market_close(coin)
            except Exception as e:
                log(f"    emergency-close err: {e}")
            return  # do not record this as a fire

    pkey = f"{coin}|{setup.side}|{setup.entry_price:.8f}"
    state['pending'][pkey] = {
        'coin': coin, 'side': setup.side,
        'entry': setup.entry_price, 'sl': setup.sl_price,
        'tp1': setup.tp1_price, 'tp2': setup.tp2_price,
        'rr1': setup.rr_to_tp1, 'rr2': setup.rr_to_tp2,
        'sl_dist_pct': setup.sl_distance_pct,
        'size': size, 'notional': notional,
        'entry_oid': entry_oid,
        'placed_t': int(time.time()*1000),
        'last_scanned_t': int(time.time()*1000),  # bookmark for fetch_1m_since
        'ob_body_top': setup.ltf_ob_body_top, 'ob_body_bottom': setup.ltf_ob_body_bottom,
        'ob_wick_top': setup.ltf_ob_wick_top, 'ob_wick_bottom': setup.ltf_ob_wick_bottom,
        'sweep_wick': setup.sweep_wick,
        'wall_present': getattr(setup, 'wall_present', False),
        'wall_usd': getattr(setup, 'wall_usd', 0),
        'path_label': getattr(setup, 'path_label', '4h'),
    }
    state['fires_total'] += 1
    path_lbl = getattr(setup, 'path_label', '4h')
    state[f'fires_path_{path_lbl}'] = state.get(f'fires_path_{path_lbl}', 0) + 1
    mark_fired(coin, setup.ltf_ob_body_top, setup.ltf_ob_body_bottom)
    save_state()  # persist immediately — a crash now would otherwise lose the fire + dedup

FEE_RT = 0.0006   # round-trip fee assumption (3bp each side)
TRACKER_TIMEOUT_S    = int(os.environ.get('TRACKER_TIMEOUT_S', '86400'))     # close as 'open_eow' after 24h
RUNNER_BE_TIMEOUT_S  = int(os.environ.get('RUNNER_BE_TIMEOUT_S', '7200'))    # force runner to BE after 2h post-TP1


def fetch_1m_since(coin, since_ms):
    """Pull 1m candles from since_ms to now."""
    raw = http_post(HL_API, {'type':'candleSnapshot','req':{
        'coin':coin,'interval':'1m','startTime':since_ms,
        'endTime':int(time.time()*1000)
    }})
    if not raw: return []
    bars = [{'t':b['t'],'o':float(b['o']),'h':float(b['h']),
             'l':float(b['l']),'c':float(b['c']),'v':float(b['v'])} for b in raw]
    bars.sort(key=lambda x: x['t'])
    return bars


def record_outcome(p, outcome, pnl_pct):
    """Append closed trade to tracker + bump counters."""
    counter_map = {
        'TP1_TP2': 'wins_tp1_tp2',
        'TP1_BE':  'wins_tp1_be',
        'TP1_BETIMEOUT': 'wins_tp1_betimeout',
        'SL':      'losses_sl',
        'EXPIRED': 'expired_unfilled',
        'OPEN_EOW': 'closed_open_eow',
    }
    state[counter_map[outcome]] += 1
    state['pnl_pct_total'] += pnl_pct
    rec = {
        'coin': p['coin'], 'side': p['side'],
        'entry': p.get('entry'), 'sl': p.get('sl'),
        'tp1': p.get('tp1'), 'tp2': p.get('tp2'),
        'rr1': p.get('rr1'), 'sl_dist_pct': p.get('sl_dist_pct'),
        'placed_t': p.get('placed_t'), 'fill_t': p.get('fill_t'),
        'closed_t': int(time.time()*1000),
        'outcome': outcome, 'pnl_pct': pnl_pct,
        'wall_present': p.get('wall_present', False),
        'wall_usd': p.get('wall_usd', 0),
        'path_label': p.get('path_label', '4h'),
    }
    state['recent_trades'].append(rec)
    if len(state['recent_trades']) > 20:
        state['recent_trades'] = state['recent_trades'][-20:]
    save_state()  # persist immediately so a mid-tick crash doesn't lose the outcome
    # 5-consec-loss blacklist: track per-coin loss streaks. Loss = pnl_pct <= 0.
    # When a coin hits BLACKLIST_LOSS_THRESHOLD (default 5) it is dropped from
    # subsequent ticks until manually reset. Sticky across restarts.
    try:
        v10_blacklist.record_outcome(p['coin'], pnl_pct, outcome=outcome)
    except Exception as _e:
        log(f"  blacklist hook err: {_e}")


def reconcile():
    """Track paper trades: fills, outcomes, expiries.

    Pending → Position when entry price is traversed (limit fill).
    Position → Closed when SL/TP1/TP2 hit (walks forward in 1m candles).
    Pending expires after SETUP_EXPIRE_S without fill.
    Position closes as OPEN_EOW after TRACKER_TIMEOUT_S without resolution.
    """
    acct = fetch_account()
    if acct:
        state['balance'] = float(acct['marginSummary']['accountValue'])

    now_ms = int(time.time()*1000)

    # --- Step 1: pending → fill detection ---
    pending_filled = []
    pending_expired = []
    for pkey, p in list(state['pending'].items()):
        age_s = (now_ms - p.get('placed_t', now_ms)) / 1000
        if age_s > SETUP_EXPIRE_S:
            pending_expired.append(pkey)
            continue
        # Fetch 1m bars only since last scan (bookmark) — falls back to placed_t for legacy entries
        since_ms = p.get('last_scanned_t') or p.get('placed_t', now_ms)
        bars = fetch_1m_since(p['coin'], since_ms)
        if not bars:
            p['last_scanned_t'] = now_ms
            continue
        entry = p['entry']; side = p['side']
        for b in bars:
            if side == 'BUY' and b['l'] <= entry:
                p['fill_t'] = b['t']; p['fill_price'] = entry
                pending_filled.append((pkey, p)); break
            if side == 'SELL' and b['h'] >= entry:
                p['fill_t'] = b['t']; p['fill_price'] = entry
                pending_filled.append((pkey, p)); break
        # Advance bookmark to last bar we examined (whether filled or not)
        p['last_scanned_t'] = bars[-1]['t']

    for pkey in pending_expired:
        p = state['pending'][pkey]
        log(f"  EXPIRE-PENDING {p['coin']} {p['side']} (no fill within {SETUP_EXPIRE_S}s)")
        record_outcome(p, 'EXPIRED', 0.0)
        del state['pending'][pkey]

    for pkey, p in pending_filled:
        log(f"  FILLED {p['coin']} {p['side']} @ {p['fill_price']:.6f}")
        p['last_scanned_t'] = p['fill_t']  # reset bookmark to fill_t so position scan starts there
        state['positions'][p['coin']] = p
        del state['pending'][pkey]

    # --- Step 2: position outcome detection ---
    closed = []
    for coin, p in list(state['positions'].items()):
        age_s = (now_ms - p.get('fill_t', now_ms)) / 1000
        # Once TP1 has hit, scan from tp1_t forward (cheaper); else scan from last bookmark
        scan_since = p.get('tp1_t') or p.get('last_scanned_t') or p.get('fill_t', now_ms)
        bars = fetch_1m_since(coin, scan_since)
        if not bars:
            if age_s > TRACKER_TIMEOUT_S:
                closed.append((coin, 'OPEN_EOW', 0.0))
            continue
        side = p['side']; entry = p['fill_price']; sl = p['sl']
        tp1 = p['tp1']; tp2 = p['tp2']

        # If TP1 already hit on a previous tick, skip the pre-TP1 search and go straight to runner watch
        if p.get('tp1_t'):
            tp1_idx = -1  # sentinel: TP1 already in the past
            sl_idx = None
        else:
            sl_idx = tp1_idx = None
            for i, b in enumerate(bars):
                if side == 'BUY':
                    if b['l'] <= sl and sl_idx is None: sl_idx = i
                    if b['h'] >= tp1 and tp1_idx is None: tp1_idx = i
                else:
                    if b['h'] >= sl and sl_idx is None: sl_idx = i
                    if b['l'] <= tp1 and tp1_idx is None: tp1_idx = i
                if sl_idx is not None or tp1_idx is not None: break
        # SL hit first (or simultaneously) → full loss
        if sl_idx is not None and (tp1_idx is None or sl_idx <= tp1_idx):
            sl_pct = (sl - entry) / entry if side == 'BUY' else (entry - sl) / entry
            closed.append((coin, 'SL', sl_pct - FEE_RT))
            continue
        # TP1 hit (now or earlier) → 50% banked, watch runner for TP2 / BE-stop / time-BE
        if tp1_idx is not None:
            # Stamp tp1_t once
            if not p.get('tp1_t'):
                p['tp1_t'] = bars[tp1_idx]['t']
                p['tp1_partial_pnl'] = 0.5 * (((tp1 - entry)/entry if side == 'BUY' else (entry - tp1)/entry) - FEE_RT/2)
            tp1_pct = (tp1 - entry) / entry if side == 'BUY' else (entry - tp1) / entry
            partial = p.get('tp1_partial_pnl', 0.5 * (tp1_pct - FEE_RT/2))
            outcome = None; runner_pnl = 0.0
            # Walk runner candles — start either after tp1_idx (if hit this tick) or from the very start of bars (subsequent ticks, scan_since == tp1_t)
            start_j = tp1_idx + 1 if tp1_idx >= 0 else 0
            for j in range(start_j, len(bars)):
                b = bars[j]
                if side == 'BUY':
                    if b['l'] <= entry:
                        outcome = 'TP1_BE'; runner_pnl = 0.5 * (0.0 - FEE_RT/2); break
                    if b['h'] >= tp2:
                        tp2_pct = (tp2 - entry) / entry
                        outcome = 'TP1_TP2'; runner_pnl = 0.5 * (tp2_pct - FEE_RT/2); break
                else:
                    if b['h'] >= entry:
                        outcome = 'TP1_BE'; runner_pnl = 0.5 * (0.0 - FEE_RT/2); break
                    if b['l'] <= tp2:
                        tp2_pct = (entry - tp2) / entry
                        outcome = 'TP1_TP2'; runner_pnl = 0.5 * (tp2_pct - FEE_RT/2); break
            if outcome is None:
                # Runner still open — apply hard-BE timeout if too long since TP1
                runner_age_s = (now_ms - p.get('tp1_t', now_ms)) / 1000
                if runner_age_s > RUNNER_BE_TIMEOUT_S:
                    outcome = 'TP1_BETIMEOUT'; runner_pnl = 0.5 * (0.0 - FEE_RT/2)
                else:
                    # leave position in state, advance bookmark to last bar
                    p['last_scanned_t'] = bars[-1]['t']
                    continue
            closed.append((coin, outcome, partial + runner_pnl))
            continue
        # Neither SL nor TP yet — advance bookmark, then check tracker timeout
        p['last_scanned_t'] = bars[-1]['t']
        if age_s > TRACKER_TIMEOUT_S:
            last = bars[-1]['c']
            unr = (last - entry) / entry if side == 'BUY' else (entry - last) / entry
            closed.append((coin, 'OPEN_EOW', unr - FEE_RT))

    for coin, outcome, pnl_pct in closed:
        p = state['positions'][coin]
        record_outcome(p, outcome, pnl_pct)
        log(f"  CLOSE {coin} {p['side']} [{p.get('path_label','?')}] wall={'+' if p.get('wall_present') else '-'} "
            f"→ {outcome} pnl={pnl_pct*100:+.2f}% rr1={p.get('rr1',0):.2f}")
        del state['positions'][coin]

def tick():
    reconcile()
    refresh_hl_volumes()  # volume-driven wall threshold; rate-limited internally
    state['tick_count'] += 1
    # Periodic blacklist visibility — log every 20 ticks
    if state['tick_count'] % 20 == 1:
        bl = v10_blacklist.get_state_snapshot()
        if bl['blacklisted_count'] or bl['consec_losses']:
            log(f"  blacklist: threshold={bl['threshold']} "
                f"blacklisted={bl['blacklisted_count']} "
                f"consec_losses={bl['consec_losses']}")
    state['last_tick_t'] = int(time.time()*1000)

    # Council Fix 3: regime gate. Classify once per tick from BTC 5m bars.
    # V10 SMC framework only fires in non-trend regimes (range/chop).
    cur_regime = 'chop'
    if REGIME_GATE:
        try:
            btc_bars = get_candles_cached('BTC', '5m', 7)
            if len(btc_bars) >= 200:
                cur_regime = classify_regime(btc_bars)
        except Exception as e:
            log(f"  regime classify err: {e}")
    state['regime'] = cur_regime

    log(f"━━ TICK #{state['tick_count']} ━━")
    log(f"Bal:${state['balance']:.2f} Pos:{len(state['positions'])} Pend:{len(state['pending'])} | "
        f"Total fires:{state['fires_total']} (4h:{state.get('fires_path_4h',0)} 1h:{state.get('fires_path_1h',0)}) "
        f"Qualified:{state['qualified_setups']} Wall+:{state['wall_present']} Wall-:{state['wall_absent']}")
    # Win/loss tracker (paper)
    wins = state['wins_tp1_tp2'] + state['wins_tp1_be'] + state['wins_tp1_betimeout']
    losses = state['losses_sl']
    closed_count = wins + losses + state['expired_unfilled'] + state['closed_open_eow']
    wr = (wins / max(1, wins + losses)) * 100 if (wins + losses) else 0
    log(f"  Tracker: closed={closed_count} (W:{state['wins_tp1_tp2']}+{state['wins_tp1_be']}+{state['wins_tp1_betimeout']}/L:{state['losses_sl']}/EXP:{state['expired_unfilled']}/EOW:{state['closed_open_eow']}) "
        f"WR={wr:.0f}% PnL%={state['pnl_pct_total']*100:+.2f}")
    sd = state['stage_drops']
    log(f"  Drops: zones={sd['no_zones']} not_at_zone={sd['not_at_zone']} mtf_block={sd['mtf_block']} no_ltf={sd['no_ltf']} build_fail={sd['build_setup_fail']}")
    ld = state['ltf_drops']
    log(f"  LTF-drops: piv={ld['no_pivots']} atr={ld['no_atr']} sweep={ld['no_sweep']} window={ld['no_local_window']} mss={ld['no_mss']} ob={ld['no_ob_window']}")
    bd = state.get('build_fail_drops', {})
    if any(bd.values()):
        log(f"  Build-drops: rr_low={bd.get('rr_too_low',0)} no_tp={bd.get('no_tp_at_all',0)} wrong_side={bd.get('wrong_side_tp',0)} risk_high={bd.get('risk_over_10pct',0)}")
    # Council #3 diagnostic surfacing
    ms = state.get('micro_samples', 0)
    bfh = state.get('build_fail_history', [])
    log(f"  Diagnostic: micro_samples={ms} build_fail_history={len(bfh)}/50")
    if bfh:
        # Quick aggregates over last-50 fails
        rr_vals = [r['rr1'] for r in bfh if 'rr1' in r]
        sl_vals = [r['sl_dist_pct'] for r in bfh if 'sl_dist_pct' in r]
        tp1_vals = [r['tp1_dist_pct'] for r in bfh if 'tp1_dist_pct' in r]
        if rr_vals:
            avg_rr = sum(rr_vals)/len(rr_vals)
            avg_sl = sum(sl_vals)/len(sl_vals)
            avg_tp1 = sum(tp1_vals)/len(tp1_vals)
            log(f"  BFH-stats: avg_rr={avg_rr:.2f} avg_sl={avg_sl:.2f}% avg_tp1={avg_tp1:.2f}% (n={len(rr_vals)})")
    # Rolling close summary: split WR/PnL by path and wall flag
    rt = state.get('recent_trades', [])
    if rt:
        def bucket(filtfn, label):
            sub = [t for t in rt if filtfn(t)]
            if not sub: return f"{label}:0"
            wins = sum(1 for t in sub if t['pnl_pct'] > 0)
            wr = round(100*wins/len(sub))
            pnl = sum(t['pnl_pct'] for t in sub)*100
            return f"{label}:{len(sub)}({wr}%, {pnl:+.2f}%)"
        log(f"  Recent({len(rt)}): "
            f"{bucket(lambda t: t.get('path_label')=='4h', '4h')} "
            f"{bucket(lambda t: t.get('path_label')=='1h', '1h')} | "
            f"{bucket(lambda t: t.get('wall_present'), 'W+')} "
            f"{bucket(lambda t: not t.get('wall_present'), 'W-')} | "
            f"{bucket(lambda t: t.get('side')=='BUY', 'BUY')} "
            f"{bucket(lambda t: t.get('side')=='SELL', 'SELL')}")

    coins_this_tick_raw = coins_for_tick(state['tick_count'], COINS)
    coins_this_tick = v10_blacklist.filter_universe(coins_this_tick_raw)
    blacklisted = v10_blacklist.get_blacklisted()
    skipped = len(coins_this_tick_raw) - len(coins_this_tick)
    log(f"Scanning {len(coins_this_tick)}/{len(COINS)} coins this tick "
        f"(regime={state.get('regime','?')}, blacklisted={len(blacklisted)}"
        f"{' skipped:'+str(skipped) if skipped else ''})")

    # Council Fix 3: skip framework if BTC is in trend regime — SMC's mean-reversion premise breaks
    if REGIME_GATE and not is_v10_allowed(state.get('regime', 'chop')):
        log(f"  REGIME-BLOCK: regime={state.get('regime')} — V10 only fires in range/chop")
        state['regime_blocks'] = state.get('regime_blocks', 0) + 1
        save_state()
        return

    setups = []
    with ThreadPoolExecutor(max_workers=SCAN_WORKERS) as ex:
        for setup in ex.map(evaluate_coin, coins_this_tick):
            if setup is not None: setups.append(setup)

    log(f"Setups generated: {len(setups)}")
    for s in setups:
        place_setup(s)

    save_state()

def main():
    log("=== POLE RUNNER V10 (FRAMEWORK) START ===")
    log(f"  PRECOG_URL: {PRECOG_URL}")
    log(f"  COINS: {len(COINS)}")
    log(f"  DRY_RUN: {DRY_RUN}, LIVE: {LIVE}")
    log(f"  RISK_PCT: {RISK_PCT}, MAX_NOT_PCT: {MAX_NOTIONAL_PCT}, LEVERAGE: {LEVERAGE}")
    log(f"  FIXED_NOTIONAL_USD: ${FIXED_NOTIONAL_USD} {'(active — bypasses RISK_PCT)' if FIXED_NOTIONAL_USD > 0 else '(disabled)'}")
    log(f"  MAX_POS: {MAX_POSITIONS}, MAX_PENDING: {MAX_PENDING}")
    log(f"  POLL_INTERVAL_S: {POLL_INTERVAL_S}, SCAN_WORKERS: {SCAN_WORKERS}")
    log(f"  WALL_CONFLUENCE: {WALL_CONFLUENCE}, MIN_WALL_USD: ${MIN_WALL_USD}")
    log(f"  DIAGNOSTIC_DIR_FILTER: {DIAGNOSTIC_DIR_FILTER}")
    log(f"  SETUP_EXPIRE_S: {SETUP_EXPIRE_S}, RUNNER_BE_TIMEOUT_S: {RUNNER_BE_TIMEOUT_S}, TRACKER_TIMEOUT_S: {TRACKER_TIMEOUT_S}")
    log(f"  STATE_FILE: {STATE_FILE}")
    log(f"  WALLET: {WALLET[:10]+'...' if WALLET else 'NONE'}")
    fetch_tick_sizes()
    load_state()
    global EXCHANGE
    EXCHANGE = init_sdk()
    while True:
        try: tick()
        except Exception as e:
            log(f"tick err: {e}"); traceback.print_exc()
        # Push state snapshot to precog for landing-page visibility (fire-and-forget)
        try: _push_state_async()
        except Exception: pass
        log(f"sleeping {POLL_INTERVAL_S}s")
        time.sleep(POLL_INTERVAL_S)

if __name__ == '__main__':
    main()
