"""PreCog regime configs — 15m OOS walk-forward tuned.

Generated: 2026-04-23 (replaces 5m-tuned file)
Method: Grid search (engine × RH/RL × TP/SL) × 5 regimes × 120 coins
Walk-forward split: 70% train / 30% test
Pass gate: test_n>=10, test_wr>=0.55, train_wr>=0.55, R:R 2.0-3.0
Storm regimes fall back to matching calm regime (insufficient OOS storm samples)
"""

REGIME_CONFIGS = { 'AAVE': { 'bull-calm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 19,
                           'pnl': 0.24,
                           'score': 0.606,
                           'sigs': ['BB'],
                           'wr': 0.579},
            'bull-storm': { 'RH': 75,
                            'RL': 25,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 19,
                            'pnl': 0.24,
                            'score': 0.606,
                            'sigs': ['BB'],
                            'wr': 0.579}},
  'AERO': { 'bear-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.015,
                            'TP': 0.03,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 12,
                            'pnl': 0.135,
                            'score': 0.273,
                            'sigs': ['BB'],
                            'wr': 0.583},
            'bull-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.015,
                            'TP': 0.03,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 12,
                            'pnl': 0.135,
                            'score': 0.273,
                            'sigs': ['BB'],
                            'wr': 0.583},
            'chop': { 'RH': 72,
                      'RL': 28,
                      'SL': 0.015,
                      'TP': 0.03,
                      'flt': 'none',
                      'n': 12,
                      'pnl': 0.135,
                      'score': 0.273,
                      'sigs': ['BB'],
                      'wr': 0.583}},
  'ALT': { 'bear-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 12,
                           'pnl': 0.2466,
                           'score': 0.57,
                           'sigs': ['PV'],
                           'wr': 0.667},
           'bull-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 12,
                           'pnl': 0.2466,
                           'score': 0.57,
                           'sigs': ['PV'],
                           'wr': 0.667},
           'chop': { 'RH': 70,
                     'RL': 30,
                     'SL': 0.025,
                     'TP': 0.05,
                     'flt': 'none',
                     'n': 12,
                     'pnl': 0.2466,
                     'score': 0.57,
                     'sigs': ['PV'],
                     'wr': 0.667}},
  'ARK': { 'bull-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.025,
                          'TP': 0.05,
                          'flt': 'none',
                          'n': 14,
                          'pnl': 0.1531,
                          'score': 0.532,
                          'sigs': ['PV'],
                          'wr': 0.929},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 14,
                           'pnl': 0.1531,
                           'score': 0.532,
                           'sigs': ['PV'],
                           'wr': 0.929}},
  'ASTER': { 'bear-storm': { 'RH': 68,
                             'RL': 32,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 28,
                             'pnl': 0.0417,
                             'score': 0.126,
                             'sigs': ['BB'],
                             'wr': 0.571},
             'bull-calm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.02,
                            'TP': 0.04,
                            'flt': 'none',
                            'n': 31,
                            'pnl': 0.3904,
                            'score': 1.472,
                            'sigs': ['BB'],
                            'wr': 0.677},
             'bull-storm': { 'RH': 72,
                             'RL': 28,
                             'SL': 0.02,
                             'TP': 0.04,
                             '_fallback_from': 'bull-calm',
                             'flt': 'none',
                             'n': 31,
                             'pnl': 0.3904,
                             'score': 1.472,
                             'sigs': ['BB'],
                             'wr': 0.677},
             'chop': { 'RH': 68,
                       'RL': 32,
                       'SL': 0.03,
                       'TP': 0.08,
                       'flt': 'none',
                       'n': 28,
                       'pnl': 0.0417,
                       'score': 0.126,
                       'sigs': ['BB'],
                       'wr': 0.571}},
  'ATOM': { 'bull-calm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 24,
                           'pnl': 0.0509,
                           'score': 0.156,
                           'sigs': ['BB'],
                           'wr': 0.625},
            'bull-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 24,
                            'pnl': 0.0509,
                            'score': 0.156,
                            'sigs': ['BB'],
                            'wr': 0.625}},
  'AVAX': { 'bull-calm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 17,
                           'pnl': 0.2334,
                           'score': 0.623,
                           'sigs': ['BB'],
                           'wr': 0.647},
            'bull-storm': { 'RH': 75,
                            'RL': 25,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 17,
                            'pnl': 0.2334,
                            'score': 0.623,
                            'sigs': ['BB'],
                            'wr': 0.647}},
  'AXS': { 'bear-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 10,
                           'pnl': 0.2914,
                           'score': 0.553,
                           'sigs': ['BB'],
                           'wr': 0.6},
           'bull-calm': { 'RH': 70,
                          'RL': 30,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 25,
                          'pnl': 0.237,
                          'score': 0.759,
                          'sigs': ['BB'],
                          'wr': 0.64},
           'bull-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 25,
                           'pnl': 0.237,
                           'score': 0.759,
                           'sigs': ['BB'],
                           'wr': 0.64},
           'chop': { 'RH': 72,
                     'RL': 28,
                     'SL': 0.03,
                     'TP': 0.08,
                     'flt': 'none',
                     'n': 10,
                     'pnl': 0.2914,
                     'score': 0.553,
                     'sigs': ['BB'],
                     'wr': 0.6}},
  'BCH': { 'bear-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 14,
                          'pnl': 0.1848,
                          'score': 0.444,
                          'sigs': ['BB'],
                          'wr': 0.643},
           'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bear-calm',
                           'flt': 'none',
                           'n': 14,
                           'pnl': 0.1848,
                           'score': 0.444,
                           'sigs': ['BB'],
                           'wr': 0.643},
           'bull-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.025,
                          'TP': 0.05,
                          'flt': 'none',
                          'n': 36,
                          'pnl': 0.0746,
                          'score': 0.274,
                          'sigs': ['BB'],
                          'wr': 0.611},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 36,
                           'pnl': 0.0746,
                           'score': 0.274,
                           'sigs': ['BB'],
                           'wr': 0.611}},
  'BLAST': { 'bear-storm': { 'RH': 70,
                             'RL': 30,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 22,
                             'pnl': 0.2554,
                             'score': 0.762,
                             'sigs': ['BB'],
                             'wr': 0.636},
             'bull-storm': { 'RH': 70,
                             'RL': 30,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 22,
                             'pnl': 0.2554,
                             'score': 0.762,
                             'sigs': ['BB'],
                             'wr': 0.636},
             'chop': { 'RH': 70,
                       'RL': 30,
                       'SL': 0.03,
                       'TP': 0.08,
                       'flt': 'none',
                       'n': 22,
                       'pnl': 0.2554,
                       'score': 0.762,
                       'sigs': ['BB'],
                       'wr': 0.636}},
  'BRETT': { 'bear-storm': { 'RH': 72,
                             'RL': 28,
                             'SL': 0.025,
                             'TP': 0.05,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 10,
                             'pnl': 0.2226,
                             'score': 0.422,
                             'sigs': ['BB'],
                             'wr': 0.6},
             'bull-storm': { 'RH': 72,
                             'RL': 28,
                             'SL': 0.025,
                             'TP': 0.05,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 10,
                             'pnl': 0.2226,
                             'score': 0.422,
                             'sigs': ['BB'],
                             'wr': 0.6},
             'chop': { 'RH': 72,
                       'RL': 28,
                       'SL': 0.025,
                       'TP': 0.05,
                       'flt': 'none',
                       'n': 10,
                       'pnl': 0.2226,
                       'score': 0.422,
                       'sigs': ['BB'],
                       'wr': 0.6}},
  'BTC': { 'bull-calm': { 'RH': 75,
                          'RL': 25,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 26,
                          'pnl': 0.0873,
                          'score': 0.291,
                          'sigs': ['BB'],
                          'wr': 0.654},
           'bull-storm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 26,
                           'pnl': 0.0873,
                           'score': 0.291,
                           'sigs': ['BB'],
                           'wr': 0.654}},
  'CAKE': { 'bull-calm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 45,
                           'pnl': 0.4001,
                           'score': 1.491,
                           'sigs': ['BB'],
                           'wr': 0.556},
            'bull-storm': { 'RH': 70,
                            'RL': 30,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 45,
                            'pnl': 0.4001,
                            'score': 1.491,
                            'sigs': ['BB'],
                            'wr': 0.556}},
  'CC': { 'bear-storm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.03,
                          'TP': 0.08,
                          '_fallback_from': 'chop',
                          'flt': 'none',
                          'n': 27,
                          'pnl': 0.1941,
                          'score': 0.56,
                          'sigs': ['BB'],
                          'wr': 0.556},
          'bull-storm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.03,
                          'TP': 0.08,
                          '_fallback_from': 'chop',
                          'flt': 'none',
                          'n': 27,
                          'pnl': 0.1941,
                          'score': 0.56,
                          'sigs': ['BB'],
                          'wr': 0.556},
          'chop': { 'RH': 72,
                    'RL': 28,
                    'SL': 0.03,
                    'TP': 0.08,
                    'flt': 'none',
                    'n': 27,
                    'pnl': 0.1941,
                    'score': 0.56,
                    'sigs': ['BB'],
                    'wr': 0.556}},
  'DOT': { 'bull-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 29,
                          'pnl': 0.2889,
                          'score': 0.912,
                          'sigs': ['BB'],
                          'wr': 0.586},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 29,
                           'pnl': 0.2889,
                           'score': 0.912,
                           'sigs': ['BB'],
                           'wr': 0.586}},
  'DYM': { 'bull-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 21,
                          'pnl': 0.3104,
                          'score': 0.948,
                          'sigs': ['BB'],
                          'wr': 0.667},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 21,
                           'pnl': 0.3104,
                           'score': 0.948,
                           'sigs': ['BB'],
                           'wr': 0.667}},
  'GALA': { 'bull-calm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 20,
                           'pnl': 0.0999,
                           'score': 0.246,
                           'sigs': ['BB'],
                           'wr': 0.55},
            'bull-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 20,
                            'pnl': 0.0999,
                            'score': 0.246,
                            'sigs': ['BB'],
                            'wr': 0.55}},
  'GMT': { 'bull-calm': { 'RH': 75,
                          'RL': 25,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 16,
                          'pnl': 0.18,
                          'score': 0.495,
                          'sigs': ['BB'],
                          'wr': 0.688},
           'bull-storm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 16,
                           'pnl': 0.18,
                           'score': 0.495,
                           'sigs': ['BB'],
                           'wr': 0.688}},
  'HBAR': { 'bear-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 13,
                            'pnl': -0.0381,
                            'score': -0.084,
                            'sigs': ['PV'],
                            'wr': 0.615},
            'bull-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 13,
                            'pnl': -0.0381,
                            'score': -0.084,
                            'sigs': ['PV'],
                            'wr': 0.615},
            'chop': { 'RH': 68,
                      'RL': 32,
                      'SL': 0.03,
                      'TP': 0.08,
                      'flt': 'none',
                      'n': 13,
                      'pnl': -0.0381,
                      'score': -0.084,
                      'sigs': ['PV'],
                      'wr': 0.615}},
  'HMSTR': { 'bear-storm': { 'RH': 72,
                             'RL': 28,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 16,
                             'pnl': 0.3128,
                             'score': 0.782,
                             'sigs': ['BB'],
                             'wr': 0.625},
             'bull-storm': { 'RH': 72,
                             'RL': 28,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 16,
                             'pnl': 0.3128,
                             'score': 0.782,
                             'sigs': ['BB'],
                             'wr': 0.625},
             'chop': { 'RH': 72,
                       'RL': 28,
                       'SL': 0.03,
                       'TP': 0.08,
                       'flt': 'none',
                       'n': 16,
                       'pnl': 0.3128,
                       'score': 0.782,
                       'sigs': ['BB'],
                       'wr': 0.625}},
  'INJ': { 'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.02,
                           'TP': 0.04,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 11,
                           'pnl': 0.2103,
                           'score': 0.507,
                           'sigs': ['PV'],
                           'wr': 0.727},
           'bull-calm': { 'RH': 70,
                          'RL': 30,
                          'SL': 0.025,
                          'TP': 0.05,
                          'flt': 'none',
                          'n': 33,
                          'pnl': 0.4946,
                          'score': 1.98,
                          'sigs': ['BB'],
                          'wr': 0.697},
           'bull-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 33,
                           'pnl': 0.4946,
                           'score': 1.98,
                           'sigs': ['BB'],
                           'wr': 0.697},
           'chop': { 'RH': 68,
                     'RL': 32,
                     'SL': 0.02,
                     'TP': 0.04,
                     'flt': 'none',
                     'n': 11,
                     'pnl': 0.2103,
                     'score': 0.507,
                     'sigs': ['PV'],
                     'wr': 0.727}},
  'KAS': { 'bear-calm': { 'RH': 70,
                          'RL': 30,
                          'SL': 0.02,
                          'TP': 0.04,
                          'flt': 'none',
                          'n': 10,
                          'pnl': 0.2067,
                          'score': 0.458,
                          'sigs': ['BB'],
                          'wr': 0.7},
           'bear-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.02,
                           'TP': 0.04,
                           '_fallback_from': 'bear-calm',
                           'flt': 'none',
                           'n': 10,
                           'pnl': 0.2067,
                           'score': 0.458,
                           'sigs': ['BB'],
                           'wr': 0.7}},
  'LINEA': { 'bull-calm': { 'RH': 70,
                            'RL': 30,
                            'SL': 0.03,
                            'TP': 0.08,
                            'flt': 'none',
                            'n': 30,
                            'pnl': 0.3222,
                            'score': 1.118,
                            'sigs': ['BB'],
                            'wr': 0.633},
             'bull-storm': { 'RH': 70,
                             'RL': 30,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'bull-calm',
                             'flt': 'none',
                             'n': 30,
                             'pnl': 0.3222,
                             'score': 1.118,
                             'sigs': ['BB'],
                             'wr': 0.633}},
  'LTC': { 'bull-calm': { 'RH': 70,
                          'RL': 30,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 34,
                          'pnl': 0.3281,
                          'score': 1.407,
                          'sigs': ['BB'],
                          'wr': 0.735},
           'bull-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 34,
                           'pnl': 0.3281,
                           'score': 1.407,
                           'sigs': ['BB'],
                           'wr': 0.735}},
  'MANTA': { 'bear-storm': { 'RH': 70,
                             'RL': 30,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'chop',
                             'flt': 'none',
                             'n': 32,
                             'pnl': 0.1945,
                             'score': 0.619,
                             'sigs': ['BB'],
                             'wr': 0.562},
             'bull-calm': { 'RH': 70,
                            'RL': 30,
                            'SL': 0.03,
                            'TP': 0.08,
                            'flt': 'none',
                            'n': 12,
                            'pnl': 0.0223,
                            'score': 0.052,
                            'sigs': ['BB'],
                            'wr': 0.667},
             'bull-storm': { 'RH': 70,
                             'RL': 30,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'bull-calm',
                             'flt': 'none',
                             'n': 12,
                             'pnl': 0.0223,
                             'score': 0.052,
                             'sigs': ['BB'],
                             'wr': 0.667},
             'chop': { 'RH': 70,
                       'RL': 30,
                       'SL': 0.03,
                       'TP': 0.08,
                       'flt': 'none',
                       'n': 32,
                       'pnl': 0.1945,
                       'score': 0.619,
                       'sigs': ['BB'],
                       'wr': 0.562}},
  'MAV': { 'bear-calm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 15,
                          'pnl': 0.2432,
                          'score': 0.565,
                          'sigs': ['BB'],
                          'wr': 0.6},
           'bear-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bear-calm',
                           'flt': 'none',
                           'n': 15,
                           'pnl': 0.2432,
                           'score': 0.565,
                           'sigs': ['BB'],
                           'wr': 0.6}},
  'ME': { 'bull-calm': { 'RH': 70,
                         'RL': 30,
                         'SL': 0.025,
                         'TP': 0.05,
                         'flt': 'none',
                         'n': 12,
                         'pnl': 0.0565,
                         'score': 0.114,
                         'sigs': ['BB'],
                         'wr': 0.583},
          'bull-storm': { 'RH': 70,
                          'RL': 30,
                          'SL': 0.025,
                          'TP': 0.05,
                          '_fallback_from': 'bull-calm',
                          'flt': 'none',
                          'n': 12,
                          'pnl': 0.0565,
                          'score': 0.114,
                          'sigs': ['BB'],
                          'wr': 0.583}},
  'MEGA': { 'bear-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.015,
                            'TP': 0.03,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 11,
                            'pnl': 0.119,
                            'score': 0.287,
                            'sigs': ['PV'],
                            'wr': 0.727},
            'bull-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.015,
                            'TP': 0.03,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 11,
                            'pnl': 0.119,
                            'score': 0.287,
                            'sigs': ['PV'],
                            'wr': 0.727},
            'chop': { 'RH': 72,
                      'RL': 28,
                      'SL': 0.015,
                      'TP': 0.03,
                      'flt': 'none',
                      'n': 11,
                      'pnl': 0.119,
                      'score': 0.287,
                      'sigs': ['PV'],
                      'wr': 0.727}},
  'MEW': { 'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 42,
                           'pnl': 0.5598,
                           'score': 2.073,
                           'sigs': ['PV'],
                           'wr': 0.571},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 42,
                           'pnl': 0.5598,
                           'score': 2.073,
                           'sigs': ['PV'],
                           'wr': 0.571},
           'chop': { 'RH': 68,
                     'RL': 32,
                     'SL': 0.025,
                     'TP': 0.05,
                     'flt': 'none',
                     'n': 42,
                     'pnl': 0.5598,
                     'score': 2.073,
                     'sigs': ['PV'],
                     'wr': 0.571}},
  'MORPHO': { 'bear-storm': { 'RH': 70,
                              'RL': 30,
                              'SL': 0.03,
                              'TP': 0.08,
                              '_fallback_from': 'chop',
                              'flt': 'none',
                              'n': 25,
                              'pnl': 0.3991,
                              'score': 1.197,
                              'sigs': ['BB'],
                              'wr': 0.6},
              'bull-storm': { 'RH': 70,
                              'RL': 30,
                              'SL': 0.03,
                              'TP': 0.08,
                              '_fallback_from': 'chop',
                              'flt': 'none',
                              'n': 25,
                              'pnl': 0.3991,
                              'score': 1.197,
                              'sigs': ['BB'],
                              'wr': 0.6},
              'chop': { 'RH': 70,
                        'RL': 30,
                        'SL': 0.03,
                        'TP': 0.08,
                        'flt': 'none',
                        'n': 25,
                        'pnl': 0.3991,
                        'score': 1.197,
                        'sigs': ['BB'],
                        'wr': 0.6}},
  'MOVE': { 'bull-calm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.025,
                           'TP': 0.05,
                           'flt': 'none',
                           'n': 12,
                           'pnl': 0.2787,
                           'score': 0.885,
                           'sigs': ['BB'],
                           'wr': 0.917},
            'bull-storm': { 'RH': 75,
                            'RL': 25,
                            'SL': 0.025,
                            'TP': 0.05,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 12,
                            'pnl': 0.2787,
                            'score': 0.885,
                            'sigs': ['BB'],
                            'wr': 0.917}},
  'NOT': { 'bull-calm': { 'RH': 75,
                          'RL': 25,
                          'SL': 0.025,
                          'TP': 0.05,
                          'flt': 'none',
                          'n': 18,
                          'pnl': 0.3998,
                          'score': 1.131,
                          'sigs': ['PV'],
                          'wr': 0.667},
           'bull-storm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 18,
                           'pnl': 0.3998,
                           'score': 1.131,
                           'sigs': ['PV'],
                           'wr': 0.667}},
  'NXPC': { 'bear-calm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 12,
                           'pnl': 0.0226,
                           'score': 0.046,
                           'sigs': ['BB'],
                           'wr': 0.583},
            'bear-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bear-calm',
                            'flt': 'none',
                            'n': 12,
                            'pnl': 0.0226,
                            'score': 0.046,
                            'sigs': ['BB'],
                            'wr': 0.583}},
  'OP': { 'bull-calm': { 'RH': 72,
                         'RL': 28,
                         'SL': 0.03,
                         'TP': 0.08,
                         'flt': 'none',
                         'n': 11,
                         'pnl': 0.1994,
                         'score': 0.421,
                         'sigs': ['PV'],
                         'wr': 0.636},
          'bull-storm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.03,
                          'TP': 0.08,
                          '_fallback_from': 'bull-calm',
                          'flt': 'none',
                          'n': 11,
                          'pnl': 0.1994,
                          'score': 0.421,
                          'sigs': ['PV'],
                          'wr': 0.636}},
  'POL': { 'bull-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 31,
                          'pnl': 0.465,
                          'score': 1.837,
                          'sigs': ['BB'],
                          'wr': 0.71},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 31,
                           'pnl': 0.465,
                           'score': 1.837,
                           'sigs': ['BB'],
                           'wr': 0.71}},
  'PYTH': { 'bear-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 15,
                            'pnl': 0.2415,
                            'score': 0.686,
                            'sigs': ['PV'],
                            'wr': 0.733},
            'bull-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 15,
                            'pnl': 0.2415,
                            'score': 0.686,
                            'sigs': ['PV'],
                            'wr': 0.733},
            'chop': { 'RH': 68,
                      'RL': 32,
                      'SL': 0.03,
                      'TP': 0.08,
                      'flt': 'none',
                      'n': 15,
                      'pnl': 0.2415,
                      'score': 0.686,
                      'sigs': ['PV'],
                      'wr': 0.733}},
  'SAND': { 'bull-calm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 19,
                           'pnl': 0.1556,
                           'score': 0.428,
                           'sigs': ['BB'],
                           'wr': 0.632},
            'bull-storm': { 'RH': 72,
                            'RL': 28,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 19,
                            'pnl': 0.1556,
                            'score': 0.428,
                            'sigs': ['BB'],
                            'wr': 0.632}},
  'SEI': { 'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 29,
                           'pnl': 0.1599,
                           'score': 0.505,
                           'sigs': ['BB'],
                           'wr': 0.586},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 29,
                           'pnl': 0.1599,
                           'score': 0.505,
                           'sigs': ['BB'],
                           'wr': 0.586},
           'chop': { 'RH': 68,
                     'RL': 32,
                     'SL': 0.025,
                     'TP': 0.05,
                     'flt': 'none',
                     'n': 29,
                     'pnl': 0.1599,
                     'score': 0.505,
                     'sigs': ['BB'],
                     'wr': 0.586}},
  'STABLE': { 'bear-storm': { 'RH': 70,
                              'RL': 30,
                              'SL': 0.03,
                              'TP': 0.08,
                              '_fallback_from': 'chop',
                              'flt': 'none',
                              'n': 11,
                              'pnl': 0.1906,
                              'score': 0.402,
                              'sigs': ['PV'],
                              'wr': 0.636},
              'bull-calm': { 'RH': 72,
                             'RL': 28,
                             'SL': 0.03,
                             'TP': 0.08,
                             'flt': 'none',
                             'n': 23,
                             'pnl': 0.2508,
                             'score': 0.732,
                             'sigs': ['BB'],
                             'wr': 0.609},
              'bull-storm': { 'RH': 72,
                              'RL': 28,
                              'SL': 0.03,
                              'TP': 0.08,
                              '_fallback_from': 'bull-calm',
                              'flt': 'none',
                              'n': 23,
                              'pnl': 0.2508,
                              'score': 0.732,
                              'sigs': ['BB'],
                              'wr': 0.609},
              'chop': { 'RH': 70,
                        'RL': 30,
                        'SL': 0.03,
                        'TP': 0.08,
                        'flt': 'none',
                        'n': 11,
                        'pnl': 0.1906,
                        'score': 0.402,
                        'sigs': ['PV'],
                        'wr': 0.636}},
  'STRK': { 'bull-calm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 14,
                           'pnl': 0.0813,
                           'score': 0.174,
                           'sigs': ['PV'],
                           'wr': 0.571},
            'bull-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 14,
                            'pnl': 0.0813,
                            'score': 0.174,
                            'sigs': ['PV'],
                            'wr': 0.571}},
  'STX': { 'bear-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.02,
                           'TP': 0.04,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 10,
                           'pnl': 0.1064,
                           'score': 0.202,
                           'sigs': ['BB'],
                           'wr': 0.6},
           'bull-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.02,
                           'TP': 0.04,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 10,
                           'pnl': 0.1064,
                           'score': 0.202,
                           'sigs': ['BB'],
                           'wr': 0.6},
           'chop': { 'RH': 72,
                     'RL': 28,
                     'SL': 0.02,
                     'TP': 0.04,
                     'flt': 'none',
                     'n': 10,
                     'pnl': 0.1064,
                     'score': 0.202,
                     'sigs': ['BB'],
                     'wr': 0.6}},
  'SUSHI': { 'bull-calm': { 'RH': 75,
                            'RL': 25,
                            'SL': 0.03,
                            'TP': 0.08,
                            'flt': 'none',
                            'n': 21,
                            'pnl': 0.342,
                            'score': 1.045,
                            'sigs': ['BB'],
                            'wr': 0.667},
             'bull-storm': { 'RH': 75,
                             'RL': 25,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'bull-calm',
                             'flt': 'none',
                             'n': 21,
                             'pnl': 0.342,
                             'score': 1.045,
                             'sigs': ['BB'],
                             'wr': 0.667}},
  'TNSR': { 'bear-storm': { 'RH': 70,
                            'RL': 30,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 33,
                            'pnl': 0.4801,
                            'score': 1.755,
                            'sigs': ['BB'],
                            'wr': 0.636},
            'bull-calm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 17,
                           'pnl': 0.3512,
                           'score': 1.022,
                           'sigs': ['PV'],
                           'wr': 0.706},
            'bull-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 17,
                            'pnl': 0.3512,
                            'score': 1.022,
                            'sigs': ['PV'],
                            'wr': 0.706},
            'chop': { 'RH': 70,
                      'RL': 30,
                      'SL': 0.03,
                      'TP': 0.08,
                      'flt': 'none',
                      'n': 33,
                      'pnl': 0.4801,
                      'score': 1.755,
                      'sigs': ['BB'],
                      'wr': 0.636}},
  'TRX': { 'bear-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.025,
                          'TP': 0.05,
                          'flt': 'none',
                          'n': 22,
                          'pnl': 0.0284,
                          'score': 0.079,
                          'sigs': ['BB'],
                          'wr': 0.591},
           'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'bear-calm',
                           'flt': 'none',
                           'n': 22,
                           'pnl': 0.0284,
                           'score': 0.079,
                           'sigs': ['BB'],
                           'wr': 0.591},
           'bull-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.015,
                          'TP': 0.03,
                          'flt': 'none',
                          'n': 10,
                          'pnl': 0.0467,
                          'score': 0.103,
                          'sigs': ['PV'],
                          'wr': 0.7},
           'bull-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.015,
                           'TP': 0.03,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 10,
                           'pnl': 0.0467,
                           'score': 0.103,
                           'sigs': ['PV'],
                           'wr': 0.7},
           'chop': { 'RH': 68,
                     'RL': 32,
                     'SL': 0.02,
                     'TP': 0.04,
                     'flt': 'none',
                     'n': 15,
                     'pnl': 0.0178,
                     'score': 0.051,
                     'sigs': ['PV'],
                     'wr': 0.733}},
  'UMA': { 'bull-calm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 17,
                          'pnl': 0.0298,
                          'score': 0.079,
                          'sigs': ['BB'],
                          'wr': 0.647},
           'bull-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 17,
                           'pnl': 0.0298,
                           'score': 0.079,
                           'sigs': ['BB'],
                           'wr': 0.647}},
  'UNI': { 'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.025,
                           'TP': 0.05,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 11,
                           'pnl': 0.1598,
                           'score': 0.386,
                           'sigs': ['PV'],
                           'wr': 0.727},
           'bull-calm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.02,
                          'TP': 0.06,
                          'flt': 'none',
                          'n': 26,
                          'pnl': 0.4537,
                          'score': 1.424,
                          'sigs': ['BB'],
                          'wr': 0.615},
           'bull-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.02,
                           'TP': 0.06,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 26,
                           'pnl': 0.4537,
                           'score': 1.424,
                           'sigs': ['BB'],
                           'wr': 0.615},
           'chop': { 'RH': 68,
                     'RL': 32,
                     'SL': 0.025,
                     'TP': 0.05,
                     'flt': 'none',
                     'n': 11,
                     'pnl': 0.1598,
                     'score': 0.386,
                     'sigs': ['PV'],
                     'wr': 0.727}},
  'VINE': { 'bull-calm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 11,
                           'pnl': 0.3522,
                           'score': 1.062,
                           'sigs': ['BB'],
                           'wr': 0.909},
            'bull-storm': { 'RH': 75,
                            'RL': 25,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 11,
                            'pnl': 0.3522,
                            'score': 1.062,
                            'sigs': ['BB'],
                            'wr': 0.909}},
  'W': { 'bull-calm': { 'RH': 68,
                        'RL': 32,
                        'SL': 0.03,
                        'TP': 0.08,
                        'flt': 'none',
                        'n': 32,
                        'pnl': 0.5145,
                        'score': 1.637,
                        'sigs': ['BB'],
                        'wr': 0.562},
         'bull-storm': { 'RH': 68,
                         'RL': 32,
                         'SL': 0.03,
                         'TP': 0.08,
                         '_fallback_from': 'bull-calm',
                         'flt': 'none',
                         'n': 32,
                         'pnl': 0.5145,
                         'score': 1.637,
                         'sigs': ['BB'],
                         'wr': 0.562}},
  'WLFI': { 'bull-calm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 22,
                           'pnl': 0.4965,
                           'score': 1.588,
                           'sigs': ['BB'],
                           'wr': 0.682},
            'bull-storm': { 'RH': 70,
                            'RL': 30,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 22,
                            'pnl': 0.4965,
                            'score': 1.588,
                            'sigs': ['BB'],
                            'wr': 0.682}},
  'XLM': { 'bull-calm': { 'RH': 72,
                          'RL': 28,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 22,
                          'pnl': 0.112,
                          'score': 0.382,
                          'sigs': ['BB'],
                          'wr': 0.727},
           'bull-storm': { 'RH': 72,
                           'RL': 28,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 22,
                           'pnl': 0.112,
                           'score': 0.382,
                           'sigs': ['BB'],
                           'wr': 0.727}},
  'XMR': { 'bear-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 31,
                           'pnl': 0.112,
                           'score': 0.443,
                           'sigs': ['BB'],
                           'wr': 0.71},
           'bull-storm': { 'RH': 70,
                           'RL': 30,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'chop',
                           'flt': 'none',
                           'n': 31,
                           'pnl': 0.112,
                           'score': 0.443,
                           'sigs': ['BB'],
                           'wr': 0.71},
           'chop': { 'RH': 70,
                     'RL': 30,
                     'SL': 0.03,
                     'TP': 0.08,
                     'flt': 'none',
                     'n': 31,
                     'pnl': 0.112,
                     'score': 0.443,
                     'sigs': ['BB'],
                     'wr': 0.71}},
  'XRP': { 'bull-calm': { 'RH': 75,
                          'RL': 25,
                          'SL': 0.03,
                          'TP': 0.08,
                          'flt': 'none',
                          'n': 23,
                          'pnl': 0.2956,
                          'score': 1.171,
                          'sigs': ['BB'],
                          'wr': 0.826},
           'bull-storm': { 'RH': 75,
                           'RL': 25,
                           'SL': 0.03,
                           'TP': 0.08,
                           '_fallback_from': 'bull-calm',
                           'flt': 'none',
                           'n': 23,
                           'pnl': 0.2956,
                           'score': 1.171,
                           'sigs': ['BB'],
                           'wr': 0.826}},
  'YZY': { 'bear-calm': { 'RH': 68,
                          'RL': 32,
                          'SL': 0.015,
                          'TP': 0.03,
                          'flt': 'none',
                          'n': 15,
                          'pnl': 0.1956,
                          'score': 0.505,
                          'sigs': ['BB'],
                          'wr': 0.667},
           'bear-storm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.015,
                           'TP': 0.03,
                           '_fallback_from': 'bear-calm',
                           'flt': 'none',
                           'n': 15,
                           'pnl': 0.1956,
                           'score': 0.505,
                           'sigs': ['BB'],
                           'wr': 0.667}},
  'ZORA': { 'bear-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'chop',
                            'flt': 'none',
                            'n': 14,
                            'pnl': 0.1665,
                            'score': 0.356,
                            'sigs': ['PV'],
                            'wr': 0.571},
            'bull-calm': { 'RH': 68,
                           'RL': 32,
                           'SL': 0.03,
                           'TP': 0.08,
                           'flt': 'none',
                           'n': 21,
                           'pnl': 0.4893,
                           'score': 1.602,
                           'sigs': ['BB'],
                           'wr': 0.714},
            'bull-storm': { 'RH': 68,
                            'RL': 32,
                            'SL': 0.03,
                            'TP': 0.08,
                            '_fallback_from': 'bull-calm',
                            'flt': 'none',
                            'n': 21,
                            'pnl': 0.4893,
                            'score': 1.602,
                            'sigs': ['BB'],
                            'wr': 0.714},
            'chop': { 'RH': 68,
                      'RL': 32,
                      'SL': 0.03,
                      'TP': 0.08,
                      'flt': 'none',
                      'n': 14,
                      'pnl': 0.1665,
                      'score': 0.356,
                      'sigs': ['PV'],
                      'wr': 0.571}},
  'kBONK': { 'bull-calm': { 'RH': 70,
                            'RL': 30,
                            'SL': 0.03,
                            'TP': 0.08,
                            'flt': 'none',
                            'n': 10,
                            'pnl': 0.0815,
                            'score': 0.155,
                            'sigs': ['PV'],
                            'wr': 0.6},
             'bull-storm': { 'RH': 70,
                             'RL': 30,
                             'SL': 0.03,
                             'TP': 0.08,
                             '_fallback_from': 'bull-calm',
                             'flt': 'none',
                             'n': 10,
                             'pnl': 0.0815,
                             'score': 0.155,
                             'sigs': ['PV'],
                             'wr': 0.6}}}


def get_config_with_fallback(coin, regime):
    """Return (cfg, reason) or (None, reason)."""
    if coin not in REGIME_CONFIGS:
        return None, 'coin_not_tuned'
    c = REGIME_CONFIGS[coin]
    if regime in c:
        reason = 'fallback_from_' + c[regime]['_fallback_from'] if '_fallback_from' in c[regime] else 'direct'
        return c[regime], reason
    # Last-resort fallback: any regime for this coin
    if 'chop' in c:
        return c['chop'], 'chop_last_resort'
    return None, 'no_regime_match'


def coverage_stats():
    regimes = ('chop', 'bull-calm', 'bull-storm', 'bear-calm', 'bear-storm')
    out = {}
    for r in regimes:
        n = sum(1 for cfg in REGIME_CONFIGS.values() if r in cfg)
        out[r] = f"{n}/{len(REGIME_CONFIGS)} ({n*100//max(len(REGIME_CONFIGS),1)}%)"
    return out
